export const seedProducts = [
  {
    customId: "null-heavy-tee",
    name: "NULL HEAVY TEE",
    brand: "BRUTAL. CORE",
    sku: "BRT-TEE-001",
    category: "men",
    categoryLabel: "TEES",
    subcategory: "T-SHIRTS",
    subtitle: "Heavyweight 320 GSM single jersey cotton boxy tee",
    price: 3499,
    compareAt: 4299,
    rating: 4.9,
    reviewCount: 48,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["BESTSELLER", "RAW GSM"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["INK BLACK", "RAW BONE", "ACID GREY"],
    description: "Constructed from bespoke 320 GSM combed cotton with high-density ribbing. Features dropped shoulders, an architectural box silhouette, and raw double-stitched hems.",
    shortDescription: "320 GSM heavy jersey with custom architectural drape.",
    materials: ["100% Combed Cotton", "Pre-shrunk 320 GSM", "Garment dyed in Tokyo"],
    reviews: [
      { id: "r1", name: "Devon R.", rating: 5, date: "2026-03-12", body: "Drape is insane. Does not wrinkle easily and holds shape after 10 washes." },
      { id: "r2", name: "Kavya M.", rating: 5, date: "2026-03-18", body: "Thickest tee I own. Worth every rupee." }
    ],
    stock: 24,
    status: "active" as const,
    featured: true,
    trending: true,
    newArrival: false,
    createdAt: "2026-01-10T00:00:00.000Z",
  },
  {
    customId: "brutal-cargo-trouser",
    name: "TACTICAL CARGO TROUSER",
    brand: "BRUTAL. LABS",
    sku: "BRT-CRG-002",
    category: "men",
    categoryLabel: "BOTTOMS",
    subcategory: "PANTS",
    subtitle: "Double-knee reinforced 14oz ripstop utility pants",
    price: 6999,
    compareAt: 8499,
    rating: 4.8,
    reviewCount: 32,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["LIMITED", "DOUBLE-KNEE"],
    sizes: ["30", "32", "34", "36"],
    colors: ["SHADOW BLACK", "MILITARY SAGE", "CONCRETE"],
    description: "Engineered from indestructible 14oz cotton ripstop. Features 8 modular utility pockets, waterproof YKK zippers, reinforced double knees, and adjustable bungee ankles.",
    shortDescription: "14oz ripstop construction with 8 modular pockets.",
    materials: ["14oz Cotton Ripstop", "YKK Aquaguard Zippers", "Bar-tacked stress points"],
    reviews: [
      { id: "r3", name: "Aarav S.", rating: 5, date: "2026-02-28", body: "Hardware and pocket depth are top notch. Perfect fit." }
    ],
    stock: 14,
    status: "active" as const,
    featured: true,
    trending: true,
    newArrival: false,
    createdAt: "2026-01-12T00:00:00.000Z",
  },
  {
    customId: "zap-heavy-hoodie",
    name: "ZAP OVERSIZED HOODIE",
    brand: "BRUTAL. CORE",
    sku: "BRT-HD-003",
    category: "women",
    categoryLabel: "HOODIES",
    subcategory: "OUTERWEAR",
    subtitle: "450 GSM French loopback terry fleece in Cyber Yellow",
    price: 5999,
    compareAt: 7299,
    rating: 5.0,
    reviewCount: 64,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["HOT", "450 GSM"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["ZAP NEON", "MIDNIGHT PITCH", "HEATHER ASH"],
    description: "450 GSM heavyweight loopback fleece with a structured double-layer hood. Zero drawstrings for a clean architectural aesthetic.",
    shortDescription: "450 GSM structured loopback fleece with double-layer hood.",
    materials: ["100% Organic Loopback Terry", "Heavy rib cuffs", "Nickel-free hardware"],
    reviews: [
      { id: "r4", name: "Maya T.", rating: 5, date: "2026-03-01", body: "The neon color is electric and the fabric is substantial." }
    ],
    stock: 9,
    status: "active" as const,
    featured: true,
    trending: true,
    newArrival: true,
    createdAt: "2026-02-01T00:00:00.000Z",
  },
  {
    customId: "raw-canvas-crossbody",
    name: "MODULAR CHEST RIG & BAG",
    brand: "BRUTAL. LABS",
    sku: "BRT-ACC-004",
    category: "accessories",
    categoryLabel: "BAGS",
    subcategory: "ACCESSORIES",
    subtitle: "Ballistic 1000D Cordura chest utility pack",
    price: 2799,
    compareAt: 3499,
    rating: 4.7,
    reviewCount: 21,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["NEW", "CORDURA 1000D"],
    sizes: ["ONE SIZE"],
    colors: ["MATTE BLACK", "TACTICAL ORANGE"],
    description: "Constructed from 1000D ballistic Cordura with Fidlock magnetic buckle and Molle webbing attachment loops.",
    shortDescription: "1000D Cordura with quick-release magnetic clasp.",
    materials: ["1000D Ballistic Cordura", "Fidlock Clasp", "Military Nylon Webbing"],
    reviews: [
      { id: "r5", name: "Arjun N.", rating: 4.8, date: "2026-03-15", body: "Fits phone, keys, wallet and compact camera seamlessly." }
    ],
    stock: 18,
    status: "active" as const,
    featured: true,
    trending: false,
    newArrival: true,
    createdAt: "2026-02-15T00:00:00.000Z",
  },
  {
    customId: "cropped-bomber-jacket",
    name: "ACID WASH CROPPED BOMBER",
    brand: "ARCHIVE 99",
    sku: "BRT-JKT-005",
    category: "women",
    categoryLabel: "JACKETS",
    subcategory: "OUTERWEAR",
    subtitle: "Heavy insulated nylon twill with raw garment wash",
    price: 8999,
    compareAt: 10999,
    rating: 4.9,
    reviewCount: 19,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["EXCLUSIVE", "HAND DYED"],
    sizes: ["XS", "S", "M"],
    colors: ["WASHED CHARCOAL", "BURNT OLIVE"],
    description: "Cropped flight silhouette featuring high-loft Primaloft insulation, two-way heavy industrial zipper, and gathered ergonomic sleeves.",
    shortDescription: "High-loft insulated flight jacket with industrial hardware.",
    materials: ["Japanese Flight Nylon", "Primaloft Insulation", "Heavy ribbed collar"],
    reviews: [],
    stock: 7,
    status: "active" as const,
    featured: true,
    trending: true,
    newArrival: true,
    createdAt: "2026-02-20T00:00:00.000Z",
  },
  {
    customId: "brutal-trucker-cap",
    name: "RAW FOAM TRUCKER CAP",
    brand: "BRUTAL. CORE",
    sku: "BRT-ACC-006",
    category: "accessories",
    categoryLabel: "HEADWEAR",
    subtitle: "High-crown foam trucker with 3D embossed rubber patch",
    subcategory: "HEADWEAR",
    price: 1899,
    compareAt: 2499,
    rating: 4.6,
    reviewCount: 15,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=1000&q=80",
    ],
    badges: ["NEW"],
    sizes: ["ADJUSTABLE"],
    colors: ["BLACK / FLAME", "ALL BLACK"],
    description: "Deep structured crown with breathable mesh backing and custom snap closure.",
    shortDescription: "High crown structure with breathable mesh.",
    materials: ["High-density foam", "Poly mesh", "Embossed rubber logo"],
    reviews: [],
    stock: 35,
    status: "active" as const,
    featured: false,
    trending: false,
    newArrival: true,
    createdAt: "2026-03-01T00:00:00.000Z",
  },
];

export const seedTaxonomy = {
  key: "default",
  brands: ["BRUTAL. CORE", "BRUTAL. LABS", "ARCHIVE 99", "RAW HARDWARE", "VOID STUDIO"],
  categories: [
    { slug: "men", title: "MEN'S\nARCHIVE", image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80", count: 12 },
    { slug: "women", title: "WOMEN'S\nDROPS", image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80", count: 8 },
    { slug: "accessories", title: "HEAVY\nOBJECTS", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80", count: 6 },
    { slug: "outerwear", title: "WINTER\nSHELLS", image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80", count: 4 },
  ],
  categoryLabels: ["TEES", "HOODIES", "BOTTOMS", "JACKETS", "BAGS", "HEADWEAR", "FOOTWEAR"],
  subtitlePresets: [
    "Heavyweight 320 GSM single jersey cotton boxy tee",
    "Double-knee reinforced 14oz ripstop utility pants",
    "450 GSM French loopback terry fleece",
    "Ballistic 1000D Cordura utility pack",
  ],
  badges: ["NEW", "SALE", "BESTSELLER", "LIMITED", "HOT", "EXCLUSIVE", "450 GSM", "RAW GSM"],
};

export const seedCoupons = [
  {
    customId: "cpn-1",
    code: "BRUTAL10",
    type: "percent" as const,
    value: 10,
    minOrder: 2500,
    status: "active" as const,
    usageCount: 142,
  },
  {
    customId: "cpn-2",
    code: "DROP500",
    type: "flat" as const,
    value: 500,
    minOrder: 4999,
    status: "active" as const,
    usageCount: 89,
  },
  {
    customId: "cpn-3",
    code: "VIP20",
    type: "percent" as const,
    value: 20,
    minOrder: 8000,
    status: "active" as const,
    usageCount: 23,
  },
];

export const seedDemoCustomers = [
  {
    customId: "cust-demo-1",
    name: "Alex Vasan",
    email: "alex@example.com",
    password: "password123",
    phone: "+91 98765 43210",
    addresses: [
      {
        id: "addr-demo-1",
        fullName: "Alex Vasan",
        phone: "+91 98765 43210",
        address: "Flat 4B, Cyber Heights, Outer Ring Rd",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560103",
        country: "India",
        isDefault: true,
      },
      {
        id: "addr-demo-2",
        fullName: "Alex Vasan (Studio)",
        phone: "+91 98765 43210",
        address: "No. 18, Design District, Indiranagar",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560038",
        country: "India",
        isDefault: false,
      },
    ],
    defaultAddressIndex: 0,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const seedDemoOrders = [
  {
    orderNumber: "BRT-842910",
    date: "2026-03-20T14:30:00.000Z",
    customerName: "Alex Vasan",
    email: "alex@example.com",
    phone: "+91 98765 43210",
    items: [
      {
        productId: "null-heavy-tee",
        name: "NULL HEAVY TEE",
        image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80",
        size: "L",
        color: "INK BLACK",
        qty: 1,
        price: 3499,
        sku: "BRT-TEE-001",
      },
      {
        productId: "raw-canvas-crossbody",
        name: "MODULAR CHEST RIG & BAG",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80",
        size: "ONE SIZE",
        color: "MATTE BLACK",
        qty: 1,
        price: 2799,
        sku: "BRT-ACC-004",
      },
    ],
    subtotal: 6298,
    shipping: 0,
    discount: 630,
    couponCode: "BRUTAL10",
    total: 5668,
    status: "SHIPPED",
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    address: {
      fullName: "Alex Vasan",
      phone: "+91 98765 43210",
      address: "Flat 4B, Cyber Heights, Outer Ring Rd",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560103",
      country: "India",
      isDefault: true,
    },
    delivery: "EXPRESS",
    eta: "Mar 25, 2026",
    timeline: [
      { status: "PLACED", timestamp: "Mar 20, 2026 02:30 PM", title: "ORDER PLACED", note: "Authorized via UPI" },
      { status: "CONFIRMED", timestamp: "Mar 20, 2026 03:00 PM", title: "ORDER CONFIRMED", note: "Sent to fulfillment center" },
      { status: "PACKED", timestamp: "Mar 21, 2026 10:15 AM", title: "PACKAGE PACKED", note: "Sealed in protective bag" },
      { status: "SHIPPED", timestamp: "Mar 21, 2026 04:45 PM", title: "HANDED OVER TO LOGISTICS", note: "Air express in transit" },
    ],
  },
];
