/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as InfoSlugRouteImport } from './routes/info.$slug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as SuperadminCustomersRouteImport } from './routes/superadmin.customers'
import { Route as SuperadminInventoryRouteImport } from './routes/superadmin.inventory'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminOrdersIndexRouteImport } from './routes/superadmin.orders.index'
import { Route as SuperadminOrdersOrderIdRouteImport } from './routes/superadmin.orders.$orderId'
import { Route as SuperadminProductsIndexRouteImport } from './routes/superadmin.products.index'
import { Route as SuperadminProductsNewRouteImport } from './routes/superadmin.products.new'
import { Route as SuperadminProductsProductIdEditRouteImport } from './routes/superadmin.products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminCustomersRoute = SuperadminCustomersRouteImport.update({
  id: '/superadmin/customers',
  path: '/superadmin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminInventoryRoute = SuperadminInventoryRouteImport.update({
  id: '/superadmin/inventory',
  path: '/superadmin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/superadmin/settings',
  path: '/superadmin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminOrdersIndexRoute = SuperadminOrdersIndexRouteImport.update({
  id: '/superadmin/orders/',
  path: '/superadmin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminOrdersOrderIdRoute = SuperadminOrdersOrderIdRouteImport.update({
  id: '/superadmin/orders/$orderId',
  path: '/superadmin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminProductsIndexRoute = SuperadminProductsIndexRouteImport.update({
  id: '/superadmin/products/',
  path: '/superadmin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminProductsNewRoute = SuperadminProductsNewRouteImport.update({
  id: '/superadmin/products/new',
  path: '/superadmin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminProductsProductIdEditRoute =
  SuperadminProductsProductIdEditRouteImport.update({
    id: '/superadmin/products/$productId/edit',
    path: '/superadmin/products/$productId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/info/$slug': typeof InfoSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/inventory': typeof SuperadminInventoryRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/superadmin/orders/$orderId': typeof SuperadminOrdersOrderIdRoute
  '/superadmin/products/new': typeof SuperadminProductsNewRoute
  '/superadmin/orders/': typeof SuperadminOrdersIndexRoute
  '/superadmin/products/': typeof SuperadminProductsIndexRoute
  '/superadmin/products/$productId/edit': typeof SuperadminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/info/$slug': typeof InfoSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/inventory': typeof SuperadminInventoryRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/superadmin/orders/$orderId': typeof SuperadminOrdersOrderIdRoute
  '/superadmin/products/new': typeof SuperadminProductsNewRoute
  '/superadmin/orders': typeof SuperadminOrdersIndexRoute
  '/superadmin/products': typeof SuperadminProductsIndexRoute
  '/superadmin/products/$productId/edit': typeof SuperadminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/info/$slug': typeof InfoSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/inventory': typeof SuperadminInventoryRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/superadmin/orders/$orderId': typeof SuperadminOrdersOrderIdRoute
  '/superadmin/products/new': typeof SuperadminProductsNewRoute
  '/superadmin/orders/': typeof SuperadminOrdersIndexRoute
  '/superadmin/products/': typeof SuperadminProductsIndexRoute
  '/superadmin/products/$productId/edit': typeof SuperadminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/info/$slug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/superadmin/customers'
    | '/superadmin/inventory'
    | '/superadmin/login'
    | '/superadmin/settings'
    | '/superadmin/'
    | '/superadmin/orders/$orderId'
    | '/superadmin/products/new'
    | '/superadmin/orders/'
    | '/superadmin/products/'
    | '/superadmin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/info/$slug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/superadmin/customers'
    | '/superadmin/inventory'
    | '/superadmin/login'
    | '/superadmin/settings'
    | '/superadmin'
    | '/superadmin/orders/$orderId'
    | '/superadmin/products/new'
    | '/superadmin/orders'
    | '/superadmin/products'
    | '/superadmin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/info/$slug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/superadmin/customers'
    | '/superadmin/inventory'
    | '/superadmin/login'
    | '/superadmin/settings'
    | '/superadmin/'
    | '/superadmin/orders/$orderId'
    | '/superadmin/products/new'
    | '/superadmin/orders/'
    | '/superadmin/products/'
    | '/superadmin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  InfoSlugRoute: typeof InfoSlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SuperadminCustomersRoute: typeof SuperadminCustomersRoute
  SuperadminInventoryRoute: typeof SuperadminInventoryRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminOrdersOrderIdRoute: typeof SuperadminOrdersOrderIdRoute
  SuperadminProductsNewRoute: typeof SuperadminProductsNewRoute
  SuperadminOrdersIndexRoute: typeof SuperadminOrdersIndexRoute
  SuperadminProductsIndexRoute: typeof SuperadminProductsIndexRoute
  SuperadminProductsProductIdEditRoute: typeof SuperadminProductsProductIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/customers': {
      id: '/superadmin/customers'
      path: '/superadmin/customers'
      fullPath: '/superadmin/customers'
      preLoaderRoute: typeof SuperadminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/inventory': {
      id: '/superadmin/inventory'
      path: '/superadmin/inventory'
      fullPath: '/superadmin/inventory'
      preLoaderRoute: typeof SuperadminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/orders/': {
      id: '/superadmin/orders/'
      path: '/superadmin/orders'
      fullPath: '/superadmin/orders/'
      preLoaderRoute: typeof SuperadminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/orders/$orderId': {
      id: '/superadmin/orders/$orderId'
      path: '/superadmin/orders/$orderId'
      fullPath: '/superadmin/orders/$orderId'
      preLoaderRoute: typeof SuperadminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/products/': {
      id: '/superadmin/products/'
      path: '/superadmin/products'
      fullPath: '/superadmin/products/'
      preLoaderRoute: typeof SuperadminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/products/new': {
      id: '/superadmin/products/new'
      path: '/superadmin/products/new'
      fullPath: '/superadmin/products/new'
      preLoaderRoute: typeof SuperadminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/products/$productId/edit': {
      id: '/superadmin/products/$productId/edit'
      path: '/superadmin/products/$productId/edit'
      fullPath: '/superadmin/products/$productId/edit'
      preLoaderRoute: typeof SuperadminProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  InfoSlugRoute: InfoSlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SuperadminCustomersRoute: SuperadminCustomersRoute,
  SuperadminInventoryRoute: SuperadminInventoryRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminOrdersOrderIdRoute: SuperadminOrdersOrderIdRoute,
  SuperadminProductsNewRoute: SuperadminProductsNewRoute,
  SuperadminOrdersIndexRoute: SuperadminOrdersIndexRoute,
  SuperadminProductsIndexRoute: SuperadminProductsIndexRoute,
  SuperadminProductsProductIdEditRoute: SuperadminProductsProductIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
